### ISSUE TITLE
[emerg]: unknown directive ""

### ISSUE THREAD

**Issue by carlos-lehmann** [cloudfoundry/php-buildpack#847]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
"api_version": "2.166.0"
cf version 6.53.0+8e2b70a4a.2020-10-01

What version of the buildpack you are using?
v4.5.3

If you were attempting to accomplish a task, what was it you were attempting to do?
deploy an app, which is fine, but we see a lot of emerg entries in the staging process and we wonder what this is about.

What did you expect to happen?
app deploys without emerg logs:
nginx           | 2023/03/16 12:30:04 [emerg] 141#0: unknown directive "" in /home/vcap/app/nginx/conf/nginx-defaults.conf:1

What was the actual behavior?
app deploys with emerg logs:
nginx           | 2023/03/16 12:30:04 [emerg] 141#0: unknown directive "" in /home/vcap/app/nginx/conf/nginx-defaults.conf:1

I wondered whether that first empty line in your defaults: https://github.com/cloudfoundry/php-buildpack/blob/master/defaults/config/nginx/http-defaults.conf are triggering this. If someone could point me where to investigate further that would be great! Thank you!

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sophiewigmore** [comment]
Hey @carlos-lehmann for some reason I can't reproduce this error when I try locally. Do you see this when you build a simple app like https://github.com/cloudfoundry/php-buildpack/tree/master/fixtures/with_nginx? I'd be happy to put in a fix for this, but I need to be able to reproduce it.

Regardless, I think you're right, it seems like the new lines in the configuration files could be the culprit. I have no idea why they all have those empty lines. You can definitely try to make the change locally, and use our `scripts/package.sh` script if you have access to Docker, and then use that as the buildpack in your build.

**Comment by carlos-lehmann** [comment]
Thank you, will try to reproduce!

**Comment by carlos-lehmann** [comment]
Hello @sophiewigmore 

Here's how I reproduced it:
index.php
```yaml
<?php phpinfo(); ?>
``` 
.bp-config/options.json
```yaml
{
    "WEB_SERVER": "nginx"
}
```
manifest.yml
```yaml
---
applications:
- name: carlos-sample-app-php
  memory: 2G
  instances: 1
  buildpacks:
    - cloudsql_sidecar_buildpack
    - https://github.com/cloudfoundry/php-buildpack.git
  stack: cflinuxfs3
  health-check-type: process
  env:
    CLOUD_SQL_PROXY_INSTANCE: ((cloudsql_instance))
    CLOUD_SQL_PROXY_CRED_CONTENT: ((cloudsql_creds))
```
The cloudsql side car is basically a process built this way: 
```yaml
---
processes:
- type: "cloudsql_sidecar_process"
  command: "$DEPS_DIR/$DEPS_IDX/cloud_sql_proxy -instances=$CLOUD_SQL_PROXY_INSTANCE -credential_file=$DEPS_DIR/$DEPS_IDX/creds.json &"
  limits:
    memory: 800
  platforms:
    cloudfoundry:
      sidecar_for: [ "web"]
```
Where the variable DEPS_DIR is usually **/home/vcap/deps** and DEPS_IDX is the index at which position this buildpack was placed.

I then packed this into gitlab-ci pipeline and ran the following:
```yaml
  script:
      - |+
        for i in {1..10}
        do
          cf delete carlos-sample-app-php -f &> /dev/null && cf push -f manifest.yml --no-start --var cloudsql_instance=$cloudsql_instance --var cloudsql_creds=$cloudsql_creds &> /dev/null && cf start carlos-sample-app-php &> /dev/null && cf logs --recent carlos-sample-app-php | grep emerg || echo "RUN: ${i} WORKED"
        done
```
result is that altho the App deploys correctly, in 50% of the cases we get [emerg] outputs in cf logs:

RUN: 1 WORKED
   2023-03-29T20:59:02.45+0000 [APP/PROC/WEB/0] OUT 20:59:02 nginx   | 2023/03/29 20:59:02 [emerg] 98#0: unknown directive "" in /home/vcap/app/nginx/conf/fastcgi_params:1
   2023-03-29T20:59:50.36+0000 [APP/PROC/WEB/0] OUT 20:59:50 nginx   | 2023/03/29 20:59:50 [emerg] 100#0: unexpected end of file, expecting ";" or "}" in /home/vcap/app/nginx/conf/nginx.conf:2
   2023-03-29T21:00:39.52+0000 [APP/PROC/WEB/0] OUT 21:00:39 nginx   | 2023/03/29 21:00:39 [emerg] 99#0: unknown directive "" in /home/vcap/app/nginx/conf/nginx-workers.conf:1
   2023-03-29T21:01:31.72+0000 [APP/PROC/WEB/0] OUT 21:01:31 nginx   | 2023/03/29 21:01:31 [emerg] 96#0: unknown directive "" in /home/vcap/app/nginx/conf/nginx.conf:1
   2023-03-29T21:02:27.82+0000 [APP/PROC/WEB/0] OUT 21:02:27 nginx   | 2023/03/29 21:02:27 [emerg] 100#0: unknown directive "" in /home/vcap/app/nginx/conf/fastcgi_params:1
RUN: 7 WORKED
RUN: 8 WORKED
RUN: 9 WORKED
   2023-03-29T21:05:57.39+0000 [APP/PROC/WEB/0] OUT 21:05:57 nginx   | 2023/03/29 21:05:57 [emerg] 96#0: unknown directive "" in /home/vcap/app/nginx/conf/nginx.conf:1

We suspect it has to do with the sidecar but we don't know how that interferes with the log output we see
