### ISSUE TITLE
cflinuxfs4 error with bin/install-ruby and bin/install-python using grep -A 3 "name: <package-name>"

### ISSUE THREAD

**Issue by gmllt** [cloudfoundry/php-buildpack#885]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf api 3.139.0
cf cli 7.7.1+0c67e47.2023-06-17

What version of the buildpack you are using?
buildpack 4.6.x

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploy an php application with a customized buildpack that includes a specific apache module (with a modified buildpack manifest.yml)

What did you expect to happen?
The staging of the app will be successful

What was the actual behavior?
The staging of the application fail with the following error:
```
ERR tar (child): /tmp/buildpacks/d37c0773994cea63f8856b8ae9574e0d/dependencies/https___buildpacks.cloudfoundry.org_dependencies_ruby_: Cannot open: No such file or directory
ERR tar (child): Error is not recoverable: exiting now
ERR tar: Child returned status 2
ERR tar: Error is not recoverable: exiting now
ERR Failed to compile droplet: Failed to run finalize script: exit status 2
```

The two scripts used to install ruby and python when staging on cflinuxfs4 are using `grep -A 3 "name: <binary_name>"`:
```bash
grep -A 3 "name: ruby" < "$buildpack_dir/manifest.yml" | awk '/uri:/ {print $2}' | cut -d'/' -f 6
```

which works fine with the original manifest.yml:
```yaml
- name: ruby
  version: 3.0.5
  uri: https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_3.0.5_linux_x64_cflinuxfs3_098393c3.tgz
  sha256: '098393c33a20af7638ff7183bbf184daf9b207b31e39f20a7fd00466823859b3'
  cf_stacks:
  - cflinuxfs4
  source: https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.5.tar.gz
  source_sha256: 9afc6380a027a4fe1ae1a3e2eccb6b497b9c5ac0631c12ca56f9b7beb4848776
```

But in my case, the manifest.yml is rewrited and the `uri` field comes on the 4th line after `name: ruby`
```yaml
- cf_stacks:
  - cflinuxfs4
  name: ruby
  sha256: 098393c33a20af7638ff7183bbf184daf9b207b31e39f20a7fd00466823859b3
  source: https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.5.tar.gz
  source_sha256: 9afc6380a027a4fe1ae1a3e2eccb6b497b9c5ac0631c12ca56f9b7beb4848776
  uri: https://buildpacks.cloudfoundry.org/dependencies/ruby/ruby_3.0.5_linux_x64_cflinuxfs3_098393c3.tgz
  version: 3.0.5
```

To reproduce:
- Modifiy the manifest.yml to move the `name` field of ruby dépendency under the `uri` field,
- Compile the buildpack for cflinuxfs4,
- Add the buildpack to a cloudfoundry instance,
- Try to push a php app using this specific buildpack,

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction
